import * as fs from "fs";
import * as path from "path";

/**
 * Pushes ABIs and deployed addresses into the frontend as generated TypeScript.
 *
 * The frontend imports from `web/src/lib/contracts.generated.ts` and never reads
 * `artifacts/` or `deployments/` directly, so there is exactly one moment where contract
 * changes reach the UI — this script — and a stale frontend is a visible diff rather than
 * a silent mismatch at runtime.
 */

const ROOT = path.join(__dirname, "..");
const ARTIFACTS = path.join(ROOT, "artifacts", "contracts");
const DEPLOYMENTS = path.join(ROOT, "deployments");
const OUT = path.join(ROOT, "..", "web", "src", "lib", "contracts.generated.ts");

const EXPORTS: Array<{ key: string; artifact: string }> = [
  { key: "botVault", artifact: "BotVault.sol/BotVault.json" },
  { key: "strategyRouter", artifact: "StrategyRouter.sol/StrategyRouter.json" },
  { key: "strategyAdapter", artifact: "interfaces/IStrategyAdapter.sol/IStrategyAdapter.json" },
  { key: "creditStrategy", artifact: "strategies/CreditStrategy.sol/CreditStrategy.json" },
  { key: "liquidityStrategy", artifact: "strategies/LiquidityStrategy.sol/LiquidityStrategy.json" },
  { key: "tbillStrategy", artifact: "strategies/TBillStrategy.sol/TBillStrategy.json" },
  { key: "rwaToken", artifact: "mocks/MockRWAToken.sol/MockRWAToken.json" },
];

function readAbi(relative: string): unknown[] {
  const file = path.join(ARTIFACTS, relative);
  if (!fs.existsSync(file)) {
    throw new Error(`Missing artifact ${relative}. Run \`npm run build\` first.`);
  }
  return JSON.parse(fs.readFileSync(file, "utf8")).abi;
}

function readDeployments(): Record<string, unknown> {
  if (!fs.existsSync(DEPLOYMENTS)) return {};

  const out: Record<string, unknown> = {};
  for (const file of fs.readdirSync(DEPLOYMENTS)) {
    if (!file.endsWith(".json")) continue;
    const manifest = JSON.parse(fs.readFileSync(path.join(DEPLOYMENTS, file), "utf8"));
    out[String(manifest.chainId)] = {
      network: manifest.network,
      usesMocks: manifest.usesMocks,
      contracts: manifest.contracts,
      config: manifest.config,
    };
  }
  return out;
}

function main() {
  const abis = Object.fromEntries(EXPORTS.map(({ key, artifact }) => [key, readAbi(artifact)]));
  const deployments = readDeployments();

  const banner = `// AUTO-GENERATED by contracts/scripts/exportAbi.ts — do not edit by hand.
// Regenerate with:  cd contracts && npm run build && npm run export-abi
// Generated ${new Date().toISOString()}
`;

  const body = `${banner}
export const abis = ${JSON.stringify(abis, null, 2)} as const;

/** Deployed addresses, keyed by chain id. Empty until a deploy script has run. */
export const deployments = ${JSON.stringify(deployments, null, 2)} as const;

export type DeployedChainId = keyof typeof deployments;
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);

  const chains = Object.keys(deployments);
  console.log(`\n  Exported ${EXPORTS.length} ABIs → web/src/lib/contracts.generated.ts`);
  console.log(
    chains.length > 0
      ? `  Addresses for chain${chains.length > 1 ? "s" : ""} ${chains.join(", ")}\n`
      : `  No deployments yet — addresses will appear after the deploy script runs.\n`,
  );
}

main();
