import * as fs from "fs";
import * as path from "path";

/**
 * Pushes ABIs and deployed addresses into the frontend as generated TypeScript.
 *
 * The frontend imports from `web/src/lib/contracts.generated.ts` and never reads
 * `artifacts/` or `deployments/` directly, so there is exactly one moment where contract
 * changes reach the UI — this script — and a stale frontend is a visible diff rather than
 * a silent mismatch at runtime.
 */

const ROOT = path.join(__dirname, "..");
const ARTIFACTS = path.join(ROOT, "artifacts", "contracts");
const DEPLOYMENTS = path.join(ROOT, "deployments");
const OUT = path.join(ROOT, "..", "web", "src", "lib", "contracts.generated.ts");

const EXPORTS: Array<{ key: string; artifact: string }> = [
  { key: "botVault", artifact: "BotVault.sol/BotVault.json" },
  { key: "strategyRouter", artifact: "StrategyRouter.sol/StrategyRouter.json" },
  { key: "strategyAdapter", artifact: "interfaces/IStrategyAdapter.sol/IStrategyAdapter.json" },
  { key: "bdexLpStrategy", artifact: "strategies/BdexV2LpStrategy.sol/BdexV2LpStrategy.json" },
  { key: "bdexPair", artifact: "interfaces/IBdexV2.sol/IBdexV2Pair.json" },
  // The asset is now the chain's real USDT, so the frontend needs a plain ERC-20 surface for
  // balance, approval, symbol and decimals reads. It must be IERC20*Metadata*: plain IERC20
  // omits symbol() and decimals(), and a UI that cannot read decimals scales every number on
  // screen by the wrong power of ten.
  { key: "erc20", artifact: "@openzeppelin/contracts/token/ERC20/extensions/IERC20Metadata.sol/IERC20Metadata.json" },
];

function readAbi(relative: string): unknown[] {
  // Dependency artifacts (OpenZeppelin) sit beside `contracts/` under artifacts/, not inside.
  const file = relative.startsWith("@")
    ? path.join(ROOT, "artifacts", relative)
    : path.join(ARTIFACTS, relative);
  if (!fs.existsSync(file)) {
    throw new Error(`Missing artifact ${relative}. Run \`npm run build\` first.`);
  }
  return JSON.parse(fs.readFileSync(file, "utf8")).abi;
}

function readDeployments(): Record<string, unknown> {
  if (!fs.existsSync(DEPLOYMENTS)) return {};

  const out: Record<string, unknown> = {};
  for (const file of fs.readdirSync(DEPLOYMENTS)) {
    if (!file.endsWith(".json")) continue;
    const manifest = JSON.parse(fs.readFileSync(path.join(DEPLOYMENTS, file), "utf8"));
    out[String(manifest.chainId)] = {
      network: manifest.network,
      /** "live" for every deployment: the project has no mock yield sources to point at. */
      sources: manifest.sources ?? "live",
      asset: manifest.asset,
      dex: manifest.dex,
      contracts: manifest.contracts,
      legs: manifest.legs ?? [],
      config: manifest.config,
    };
  }
  return out;
}

function main() {
  const abis = Object.fromEntries(EXPORTS.map(({ key, artifact }) => [key, readAbi(artifact)]));
  const deployments = readDeployments();

  const banner = `// AUTO-GENERATED by contracts/scripts/exportAbi.ts — do not edit by hand.
// Regenerate with:  cd contracts && npm run build && npm run export-abi
// Generated ${new Date().toISOString()}
`;

  const body = `${banner}
export const abis = ${JSON.stringify(abis, null, 2)} as const;

/** Deployed addresses, keyed by chain id. Empty until a deploy script has run. */
export const deployments = ${JSON.stringify(deployments, null, 2)} as const;

export type DeployedChainId = keyof typeof deployments;
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, body);

  const chains = Object.keys(deployments);
  console.log(`\n  Exported ${EXPORTS.length} ABIs → web/src/lib/contracts.generated.ts`);
  console.log(
    chains.length > 0
      ? `  Addresses for chain${chains.length > 1 ? "s" : ""} ${chains.join(", ")}\n`
      : `  No deployments yet — addresses will appear after the deploy script runs.\n`,
  );
}

main();
